# Generated by Django 5.1.1 on 2024-09-14 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('highscore', models.FloatField(validators=[django.core.validators.MaxValueValidator(99999)])),
            ],
        ),
    ]
