# Generated by Django 5.1.1 on 2024-09-16 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='most_aliens_killed_in_one_game',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
