# Generated by Django 5.1.1 on 2024-09-19 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userdata_most_aliens_killed_in_one_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='highscore',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
