# Generated by Django 5.1.1 on 2024-09-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_userdata_highscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
